import { GetServerSidePropsContext, GetServerSidePropsResult } from 'next';
import Head from 'next/head';
import HomePageDesktopComponent from '../components/home/home-page-desktop.component';
import { IPrimaryCatalog } from '../models/primary-catalog.model';
import { getRequest } from '../utils/axios.utils';
import { IIsMobile, isMobile } from '../utils/device.utils';
import { IWithUser, provideUserFromApi } from '../utils/hooks/user.hook';

interface IPrimaryCatalogs extends IIsMobile, IWithUser {
  primaryCatalogs: IPrimaryCatalog[];
}

export async function getServerSideProps(
  c: GetServerSidePropsContext,
): Promise<GetServerSidePropsResult<IPrimaryCatalogs>> {
  const primaryCatalogs = await getRequest<IPrimaryCatalog[]>('catalog/primary');
  console.log((await provideUserFromApi()));
  return {
    props: {
      ...isMobile(c),
      primaryCatalogs,
      ...await provideUserFromApi(),
    },
  };
}

export default function Home({ isMobile, primaryCatalogs }: IIsMobile & IPrimaryCatalogs) {
  return (
    <>
      <Head>
        <title>Ювелирка</title>
        <meta name="description"
              content="Generated by create next app"/>
        <meta name="viewport"
              content="width=device-width, initial-scale=1"/>
        <link rel="icon"
              href="/favicon.ico"/>
      </Head>
      <main>
        <HomePageDesktopComponent primaryCatalogs={primaryCatalogs}/>
      </main>
    </>
  );
}
